# Generated by Django 2.2.17 on 2020-12-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='authorization_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
