# Generated by Django 2.2.17 on 2020-12-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='psProductCode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
