# Generated by Django 2.2.17 on 2020-12-13 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_auto_20201213_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('dateexp', models.CharField(max_length=10)),
                ('cardholder', models.CharField(max_length=150)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.ContaCorrente')),
            ],
        ),
    ]
